# -*- coding: utf-8 -*-
#
# SimplePyGed documentation build configuration file, created by
# sphinx-quickstart on Mon Oct 18 15:24:56 2010.
#
# This file is execfile()d with the current directory set to its containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

import sys, os

sys.path.append('../simplepyged/')

extensions = ['myst_parser', 'sphinx.ext.napoleon', 'sphinx_markdown_builder',
              'nbsphinx']

templates_path = ['_templates']

# General information about the project.
project = u'simplepyged'
copyright = u'2010, Nikola Skoric'

author = 'matt-chv'
release = '0.1.0'

extensions = ['myst_parser', 'sphinx.ext.napoleon', 'sphinx_markdown_builder',
              'nbsphinx']

templates_path = ['_templates']
exclude_patterns = []

add_module_names = True

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
